language: elixir

elixir:
  - 1.3.1

otp_release:
  - 18.2.1

addons:
  postgresql: "9.4"

sudo: false # to use faster container based build environment

env:
  - MIX_ENV=test

before_script:
  - mix deps.get --only test
  - mix ecto.create --quiet
  - mix ecto.migrate

script: mix coveralls.travis --umbrella

cache:
  directories:
    - _build
    - deps
