language: elixir

elixir:
  - 1.3.1

otp_release:
  - 18.2.1

addons:
  postgresql: "9.4"
  
env:
  - MIX_ENV=test

script: mix coveralls.travis --umbrella

cache:
  directories:
    - _build
    - deps
